services:
  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run shit.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - api

  api:
    build: .
    container_name: api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn shit_api:app --host 0.0.0.0 --port 8000
